fix(net/nginx): nginx 1.26.1 quic code fails to compile with gcc 15 (alpine 3.23)
/nginx-1.26.1 # ./configure \
>       --prefix=/etc/nginx \
>       --sbin-path=/usr/sbin/nginx \
>       --modules-path=/usr/lib/nginx/modules \
>       --conf-path=/etc/nginx/nginx.conf \
>       --error-log-path=/var/log/nginx/error.log \
>       --http-log-path=/var/log/nginx/access.log \
>       --pid-path=/var/run/nginx.pid \
>       --lock-path=/var/run/nginx.lock \
>       --http-client-body-temp-path=/var/cache/nginx/client_temp \
>       --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
>       --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
>       --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
>       --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
>       --user=nginx \
>       --group=nginx \
>       --with-file-aio \
>       --with-threads \
>       --with-http_addition_module \
>       --with-http_auth_request_module \
>       --with-http_dav_module \
>       --with-http_flv_module \
>       --with-http_mp4_module \
>       --with-http_gunzip_module \
>       --with-http_gzip_static_module \
>       --with-http_random_index_module \
>       --with-http_realip_module \
>       --with-http_secure_link_module \
>       --with-http_slice_module \
>       --with-http_ssl_module \
>       --with-http_stub_status_module \
>       --with-http_sub_module \
>       --with-http_v2_module \
>       --with-http_v3_module \
>       --with-stream \
>       --with-stream_realip_module \
>       --with-stream_ssl_module \
>       --with-stream_ssl_preread_module \
>       --with-cc-opt='-O3 -flto=auto' \
>       --with-ld-opt='-flto=auto -s -Wl,--build-id=none -Wl,-z,relro,-z,now -l:libssl.a -l:libcrypto.a -l:libpcre2-8.a -l:libz.a -l:libmaxmin
ddb.a' \
>       --with-compat \
>       --add-dynamic-module=/ngx_brotli \
>       --add-dynamic-module=/ngx_geoip2 \
>       --add-dynamic-module=/ngx_upstream_check \
>       --add-dynamic-module=/ngx_subs_filter \
>       --add-dynamic-module=/ngx_google_filter
checking for OS
 + Linux 6.12.24-Unraid x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 15.2.0 (Alpine 15.2.0)
checking for gcc -pipe switch ... found
checking for --with-ld-opt="-flto=auto -s -Wl,--build-id=none -Wl,-z,relro,-z,now -l:libssl.a -l:libcrypto.a -l:libpcre2-8.a -l:libz.a -l:libmaxminddb.a" ... found
checking for -Wl,-E switch ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for gcc builtin 64 bit byteswap ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... not found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... found
checking for Linux specific features
checking for epoll ... found
checking for EPOLLRDHUP ... found
checking for EPOLLEXCLUSIVE ... found
checking for eventfd() ... found
checking for O_PATH ... found
checking for sendfile() ... found
checking for sendfile64() ... found
checking for sys/prctl.h ... found
checking for prctl(PR_SET_DUMPABLE) ... found
checking for prctl(PR_SET_KEEPCAPS) ... found
checking for capabilities ... found
checking for crypt_r() ... found
checking for sys/vfs.h ... found
checking for BPF sockhash ... found
checking for SO_COOKIE ... found
checking for UDP_SEGMENT ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... found
checking for sched_yield() ... found
checking for sched_setaffinity() ... found
checking for SO_SETFIB ... not found
checking for SO_REUSEPORT ... found
checking for SO_ACCEPTFILTER ... not found
checking for SO_BINDANY ... not found
checking for IP_TRANSPARENT ... found
checking for IP_BINDANY ... not found
checking for IP_BIND_ADDRESS_NO_PORT ... found
checking for IP_RECVDSTADDR ... not found
checking for IP_SENDSRCADDR ... not found
checking for IP_PKTINFO ... found
checking for IPV6_RECVPKTINFO ... found
checking for IP_MTU_DISCOVER ... found
checking for IPV6_MTU_DISCOVER ... found
checking for IP_DONTFRAG ... not found
checking for IPV6_DONTFRAG ... found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE ... found
checking for TCP_FASTOPEN ... found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for kqueue AIO support ... not found
checking for Linux AIO support ... found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint32_t ... found
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for AF_INET6 ... found
checking for setproctitle() ... not found
checking for pread() ... found
checking for pwrite() ... found
checking for pwritev() ... found
checking for strerrordesc_np() ... not found
checking for sys_nerr ... not found
checking for _sys_nerr ... not found
checking for localtime_r() ... found
checking for clock_gettime(CLOCK_MONOTONIC) ... found
checking for posix_memalign() ... found
checking for memalign() ... found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for System V shared memory ... found
checking for POSIX semaphores ... found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for ioctl(FIONREAD) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... not found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for sysconf(_SC_LEVEL1_DCACHE_LINESIZE) ... not found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional dynamic modules
adding module in /ngx_brotli
 + ngx_brotli was configured
adding module in /ngx_geoip2
checking for MaxmindDB library ... found
 + ngx_geoip2_module was configured
adding module in /ngx_upstream_check
checking for ngx_http_upstream_check_module ... found
 + ngx_http_upstream_check_module was configured
adding module in /ngx_subs_filter
 + ngx_http_subs_filter_module was configured
adding module in /ngx_google_filter
 + ngx_http_google_filter_module was configured
checking for PCRE2 library ... found
checking for OpenSSL library ... found
checking for OpenSSL QUIC support ... not found
checking for OpenSSL QUIC compatibility ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using threads
  + using system PCRE2 library
  + using system OpenSSL library
  + using system zlib library

  nginx path prefix: "/etc/nginx"
  nginx binary file: "/usr/sbin/nginx"
  nginx modules path: "/usr/lib/nginx/modules"
  nginx configuration prefix: "/etc/nginx"
  nginx configuration file: "/etc/nginx/nginx.conf"
  nginx pid file: "/var/run/nginx.pid"
  nginx error log file: "/var/log/nginx/error.log"
  nginx http access log file: "/var/log/nginx/access.log"
  nginx http client request body temporary files: "/var/cache/nginx/client_temp"
  nginx http proxy temporary files: "/var/cache/nginx/proxy_temp"
  nginx http fastcgi temporary files: "/var/cache/nginx/fastcgi_temp"
  nginx http uwsgi temporary files: "/var/cache/nginx/uwsgi_temp"
  nginx http scgi temporary files: "/var/cache/nginx/scgi_temp"

/nginx-1.26.1 #
/nginx-1.26.1 # make -j$(nproc)
make -f objs/Makefile
make[1]: Entering directory '/nginx-1.26.1'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O3 -flto=auto -Wno-deprecated-declarations -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I /ngx_brotli/deps/brotli/c/include -I /ngx_upstream_check -I objs \
        -o objs/src/core/nginx.o \
        src/core/nginx.c
...
...
...
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O3 -flto=auto -Wno-deprecated-declarations -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I /ngx_brotli/deps/brotli/c/include -I /ngx_upstream_check -I objs \
        -o objs/src/event/quic/ngx_event_quic_connid.o \
        src/event/quic/ngx_event_quic_connid.c
src/event/quic/ngx_event_quic_protection.c: In function 'ngx_quic_keys_set_initial_secret':
src/event/quic/ngx_event_quic_protection.c:126:9: error: initializer-string for array of 'unsigned char' truncates NUL terminator but destination lacks 'nonstring' attribute (21 chars into 20 available) [-Werror=unterminated-string-initialization]
  126 |         "\x38\x76\x2c\xf7\xf5\x59\x34\xb3\x4d\x17"
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/event/quic/ngx_event_quic_protection.c: In function 'ngx_quic_create_retry_packet':
src/event/quic/ngx_event_quic_protection.c:940:9: error: initializer-string for array of 'unsigned char' truncates NUL terminator but destination lacks 'nonstring' attribute (17 chars into 16 available) [-Werror=unterminated-string-initialization]
  940 |         "\xbe\x0c\x69\x0b\x9f\x66\x57\x5a\x1d\x76\x6b\x54\xe3\x68\xc8\x4e";
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/event/quic/ngx_event_quic_protection.c:942:9: error: initializer-string for array of 'unsigned char' truncates NUL terminator but destination lacks 'nonstring' attribute (13 chars into 12 available) [-Werror=unterminated-string-initialization]
  942 |         "\x46\x15\x99\xd3\x5d\x63\x2b\xf2\x23\x98\x25\xbb";
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O3 -flto=auto -Wno-deprecated-declarations -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I /ngx_brotli/deps/brotli/c/include -I /ngx_upstream_check -I objs \
        -o objs/src/event/quic/ngx_event_quic_migration.o \
        src/event/quic/ngx_event_quic_migration.c
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1120: objs/src/event/quic/ngx_event_quic_protection.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/nginx-1.26.1'
make: *** [Makefile:10: build] Error 2
/nginx-1.26.1 #